### ISSUE TITLE
Look into better logging packages

### ISSUE THREAD

**Issue by jlin21** [apigee/henchman#1]

**Comment by sudharsh** [comment]
https://github.com/golang/glog is one

**Comment by jlin21** [comment]
https://github.com/Sirupsen/logrus

**Comment by sudharsh** [comment]
We've zeroe'd in on logrus

**Comment by jlin21** [comment]
Logrus package adds alot of unnecessary lines.  Should we consider just going back to the standard log package?  This section is slightly insightful http://peter.bourgon.org/go-in-production/#logging-and-telemetry

**Comment by jlin21** [comment]
Actually I just need to remove that logrus wrapper func. Remove the mapping of context variables and just put it as part of the error message

**Comment by sudharsh** [comment]
Do you want to re-open this? I'd say this is not that much of a priority for now. Let's come back to this at a later time. So far logrus isn't breaking anything.
