### ISSUE TITLE
Yum module can potentially lock at times

### ISSUE THREAD

**Issue by jlin21** [apigee/henchman#100]
`Existing lock /var/run/yum.pid: another copy is running` is part of the error message.

Notes/Solutions
- Make the yum module check if `/var/run/yum.pid` is active.  Wait a certain time and pass back a result stating yum is being used.
- Could be on the user end where yum is being used by a bootstrap program
- Started occuring after fix #99

**Comment by sudharsh** [comment]
Haven't seem this error occuring lately. Might have been a one-off thing. Let's re-open this if it occurs predictably.
