### ISSUE TITLE
Henchman should return exit code of the task it returned.

### ISSUE THREAD

**Issue by baskaran-md** [apigee/henchman#105]
If a task fails with non-zero exit code, Henchman still returns zero. It should actually return the exit code of that failed task.

**Comment by sudharsh** [comment]
While it should return a non-zero code, I feel it should be independent of the executed task code. In a multi-machine scenario, a given task can fail only on a certain subset of nodes.

**Comment by jlin21** [comment]
I agree with sudharsh. The tasks are run on a remote machine. Henchman should return code should be base off henchmans execution

**Comment by baskaran-md** [comment]
Why this was closed? Resolution?
