### ISSUE TITLE
henchman version is not getting updated

### ISSUE THREAD

**Issue by baskaran-md** [apigee/henchman#113]
Its for many builds..

```
henchman version 0.1.194
```

**Comment by sudharsh** [comment]
Need to pull that ldflags trick. 
@jlin21 want to take a stab at this?
http://stackoverflow.com/questions/11354518/golang-application-auto-build-versioning

**Comment by jlin21** [comment]
We have to update main.go for every feature push.  We just have to remember to change it

**Comment by jlin21** [comment]
Nvm didn't see you comment @sudharsh

**Comment by jlin21** [comment]
@sudharsh Do we want the min version to be linked with the build number of circle?  If we just want each build to be something different we it'll be easier to do.

**Comment by sudharsh** [comment]
Let's stick to commit hashes and build numbers. 1.[build].[commit]
