### ISSUE TITLE
Henchman considers the task as failed when condition doesn't match, and does retry..

### ISSUE THREAD

**Issue by baskaran-md** [apigee/henchman#120]
```
  - name: Install latest version of {{ vars.component }} RPM
    shell: cmd="yum install -y {{ vars.component }}"
    debug: true
    retry: 2
    when: vars.version == "latest"
```

Here, when the condition doesn't match, Henchman retries it for the given number of times. It should retry only when the task is executed and failed.

**Comment by baskaran-md** [comment]
The console log looks confusing..

**Comment by jlin21** [comment]
@baskaran-md for the console log do you mean the task output to screen?  Is it scrambled and out of order when there are more than one hosts running?

**Comment by jlin21** [comment]
The latest build fixes this retry issue.  If the when condition is false, it will not retry now.
