### ISSUE TITLE
Switch concurrency model

### ISSUE THREAD

**Issue by jlin21** [apigee/henchman#121]
Instead of having each machine iterate through the task list, it will have each task iterate through the machine list.

**Comment by sudharsh** [comment]
I hope we're not waiting for each finish their tasks. Things will ssloowwww as the number of machines increases

**Comment by madhurranjan** [comment]
What other choice do we have ?

**Comment by sudharsh** [comment]
I do feel that each task should iterate through the list of machines and despatch them all at once. If something bad happens we can just do a rollback.

We don't gain anything by waiting for one machine to finish all the tasks and then moving on to the other.

**Comment by jlin21** [comment]
This feature has been created and tested for standard deploy.  It will be merged to master when rolling_deploy branch is finished
