### ISSUE TITLE
[Regression] Shell command not working

### ISSUE THREAD

**Issue by baskaran-md** [apigee/henchman#135]
```
  - name: Remove Support Folders
    shell: cmd="rm -rf {{ vars.install_dir }}/{var,etc,data*}"
    ignore_errors: true
```

This is working fine on build 245 & 253. But not on latest. 255+ / 266..

**Comment by jlin21** [comment]
This should be resolved when the go shell module finishes

**Comment by jlin21** [comment]
Issue resolved when shell module was ported to go
