### ISSUE TITLE
move away from code.google.com for modules

### ISSUE THREAD

**Issue by ashokrajar** [apigee/henchman#18]
❯❯❯ go get -u github.com/apigee/henchman
warning: code.google.com is shutting down; import path code.google.com/p/go-uuid/uuid will stop working
warning: code.google.com is shutting down; import path code.google.com/p/go.crypto/ssh will stop working

code.google.com/p/go-uuid/uuid => https://github.com/pborman/uuid
code.google.com/p/go.crypto/ssh => https://godoc.org/golang.org/x/crypto/ssh

**Comment by madhurranjan** [comment]
Hey @ashokrajar  , can you just clone the repo for now and run 'go build' on it ? We've all the dependencies in GoDeps.

**Comment by sudharsh** [comment]
You might still have to run `godep restore`
