### ISSUE TITLE
Investigate the idea of modules that are not files

### ISSUE THREAD

**Issue by sudharsh** [apigee/henchman#44]
Complex modules can be a folder that has all the dependencies as part of the module directory. The entry point of such module should be an 'exec' script. Can bundle dependencies of the module as part of its directory.

Requires changes in the executor to figure out if the module being executed is a file or a directory.

**Comment by jlin21** [comment]
Right now we are using a tar and untar method.  
Current implementation issues:
- modules folder is created in ${HOME}/.henchman (maybe move all modules to a module folder?)
- does not work with current `local: true` implementation

**Comment by jlin21** [comment]
Rsync

**Comment by jlin21** [comment]
Current implementation of using Tar will not work with multiple hosts.

**Comment by jlin21** [comment]
Issue fixed.  Modules with .tar were being removed/created at the "same time".  Need to find a way to clean up tar modules after a plan finishes executing.

**Comment by jlin21** [comment]
Moving all necessary modules to all remote machines before plans are even executed.  plan.Setup() does this.
