### ISSUE TITLE
curl module

### ISSUE THREAD

**Issue by jlin21** [apigee/henchman#45]
Using only std python libs (httplib, urllib, urllib2).
httplib - is a parsing nightmare
urllib/urllib2 can only handle GET and POST

OR

Find a way to use without stdlibs that won't cause dependency probs.
Checkout issue #44 

For now have it use basic RESTful calls. 

result["output"] = {'status': status_code, 'headers': headers, 'body': body}

**Comment by madhurranjan** [comment]
Best thing is to use requests module but we should refrain from having a local pip setup if possible.

**Comment by jlin21** [comment]
After implementating issue #44 we can access the module locally. Wouldn't need to install
