### ISSUE TITLE
Shell module with ":" in the command is failing.

### ISSUE THREAD

**Issue by baskaran-md** [apigee/henchman#57]
```
2015/10/21 23:14:42 Error processing tasks - yaml: line 13: mapping values are not allowed in this context
```

**Comment by madhurranjan** [comment]
':' is a way of supporting the yaml name / value pairs. So this is to be expected. Closing this issue.

**Comment by sudharsh** [comment]
You can wrap the entire thing around quotes. We need a test case for this though
