### ISSUE TITLE
when check with 'in' and 'not in'  

### ISSUE THREAD

**Issue by madhurranjan** [apigee/henchman#65]
example:

when: "foo" in "some array"
when: "foo" not in "inv.group"

**Comment by jlin21** [comment]
Need to make a pongo2 filter for this one

**Comment by madhurranjan** [comment]
First need to check if pongo has support for this! Else need to raise a ticket there I guess?

**Comment by jlin21** [comment]
If they dont have support. They made making filters a breeze

**Comment by madhurranjan** [comment]
You have a quick link ?

**Comment by jlin21** [comment]
`in` is a supported identifier in pongo2.  As with `not`, but cannot use `not in`.  It's a bug in pongo2 I already submitted a ticket.  If we really need `not in` we can build a filter.
