### ISSUE TITLE
Add Register and When functionality

### ISSUE THREAD

**Issue by jlin21** [apigee/henchman#7]
Requires completion of main.go

**Comment by jlin21** [comment]
Added registerMap functionality.  Need to write test cases now.

**Comment by jlin21** [comment]
when will be evaluated as pongo2 without {{ }}.  {{ }} is a special notation in yaml

**Comment by jlin21** [comment]
Need integration testing for register use case

**Comment by sudharsh** [comment]
Once #19 is done, we don't need an integ test. We can just mock up a test transport.
