### ISSUE TITLE
Support for "folder" in "copy" module

### ISSUE THREAD

**Issue by baskaran-md** [apigee/henchman#72]

**Comment by jlin21** [comment]
Currently our ssh.Put only really supports copying of files.

Ideas to transfer folders:
- can be to `tar` the folder, transfer the folder, then untar
- Do our current way of passing in protocols then the bytes.  For folders this will require walking.
  *https://godoc.org/github.com/pkg/sftp this will clean up the code, but sftp will be the slowest of them all

**Comment by jlin21** [comment]
I'm going to start with a sftp implementation.

**Comment by jlin21** [comment]
We're using sftp to transfer files.

Folders are transferred by tarring the folder, transferring, then untarring
