### ISSUE TITLE
Differentiate Exec Order for standalone vs dependency modules

### ISSUE THREAD

**Issue by jlin21** [apigee/henchman#73]
Currently all modules use a the default exec order until otherwise specified.  Need to find a way to have a standalone vs non standalone exec order

**Comment by sudharsh** [comment]
Can you elaborate a little on this issue. Not catching it.

**Comment by jlin21** [comment]
```
execOrder := map[string][]string{"default": []string{"create_dir", "put_module", "exec_module"},
    "copy": []string{"create_dir", "put_module", "put_file", "copy_remote", "exec_module"},
    "template": []string{"create_dir", "put_module", "process_template", "put_file", "copy_remote",
      "reset_src", "exec_module"},
    "curl": []string{"create_dir", "tar_module", "put_tar_module", "untar_module", "exec_tar_module"},
  }
```

So any module name not in execOrder will automatically take the default order.  If a user wanted to created their own module with dependencies, they would have to insert the module name into execOrder.

**Comment by sudharsh** [comment]
That would mean editing the source code. A better solution is to have
.manifest of some sort that has the dependencies and the exec order.

On Tue, Nov 3, 2015 at 2:52 PM, jlin21 notifications@github.com wrote:

> execOrder := map[string][]string{"default": []string{"create_dir", "put_module", "exec_module"},
>     "copy": []string{"create_dir", "put_module", "put_file", "copy_remote", "exec_module"},
>     "template": []string{"create_dir", "put_module", "process_template", "put_file", "copy_remote",
>       "reset_src", "exec_module"},
>     "curl": []string{"create_dir", "tar_module", "put_tar_module", "untar_module", "exec_tar_module"},
>   }
> 
> So any module name not in execOrder will automatically take the default
> order. If a user wanted to created their own module with dependencies, they
> would have to insert the module name into execOrder.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/apigee/henchman/issues/73#issuecomment-153514417.

## 

Sudharshan S
http://sudharsh.wordpress.com

**Comment by jlin21** [comment]
That would be a solid solution. Would there be a way to specify if a module is standalone vs w/ dependencies without refactoring modules.go too much?

**Comment by jlin21** [comment]
Right now standalone modules only have the `exec_module` step and nonstandalone modules only have the `exec_tar_module` step

**Comment by jlin21** [comment]
Changed module resolve to check for "dependencies".  No more of a need for exec_tar_module
