### ISSUE TITLE
Duplicate loglevels for outputs

### ISSUE THREAD

**Issue by sudharsh** [apigee/henchman#75]
The behaviour of passing both '--debug' when using henchman from the CLI and passing 'loglevel=debug' from the tasks in some of the modules is funky. 

What happens if --debug is true but loglevel=debug is missing?
What happens if --debug is fale but loglevel=debug is present?

**Comment by jlin21** [comment]
Right now setting `--debug` just prints any statements in the `Debug` func.  `loglevel=debug` in modules is dependent on the modules.  For instance, having `loglevel=debug` for the shell module stores the stdout of the cmd executed in Result.Output , while  setting `loglevel=debug` for the curl module stores its values as a string in Result.Output as opposed to a python dict.

But yeah we need to think of a solid standard for implementing loglevel=debug in modules

**Comment by sudharsh** [comment]
Saw a case where --debug wasn't enabled but loglevel=true was set for the yum and shell module. No stdout was printed.

--debug should affect henchman's internal logging, not that of the modules.

**Comment by jlin21** [comment]
Yeah true.  Right now if `--debug` is enabled than the tasks output would be logged.  For the shell module (idk about yum) it only stored the stdout into the taskResult.Output if `loglevel=true` wouldn't really have any benefit for the user to debug unless `--debug` was also specified.

**Comment by sudharsh** [comment]
Might as well remove `loglevel=true` bits from modules then. Attach stdout to taskresult ALWAYS and let the presence of `--debug` affect the output. If all or none isn't desirable, just have a `silent` option as part of the TASK definition, not the modules.

Doing this enforces a consistent behavior w.r.t. modules output and `loglevel=true` mental overhead is removed.

**Comment by jlin21** [comment]
+1, ditto to this

**Comment by jlin21** [comment]
in a module when loglevel=debug will print out the task output regardless if the --Debug flag is true.  The --Debug should be saved for a large scale debug dump

**Comment by jlin21** [comment]
Idea for a solution:
- modules will not include a `loglevel=debug` parameter
- `--Debug` flag will activate all other Debug logs to help debug the ENTIRE execution of Henchman
- `debug` will be a field for tasks.  If set to true then `taskResult.Output` will be displayed alongside msg and state
- `debug` can also be set at a plan level

**Comment by jlin21** [comment]
need to make tests for this
