### ISSUE TITLE
Henchman artifacts are missing in circleci.

### ISSUE THREAD

**Issue by baskaran-md** [apigee/henchman#85]
No artifacts @ https://circleci.com/gh/apigee/henchman/124#artifacts

Last artifact found for master @ https://circleci.com/gh/apigee/henchman/104#artifacts

**Comment by jlin21** [comment]
https://discuss.circleci.com/t/artifacts-not-getting-collected/465/10

Someone had a similar issue and had to manually transfer artifacts. So package.sh now transfers artifacts.
